services:
  - type: web
    name: pryMongoEsp32
    runtime: python
    repo: https://github.com/uriel806/SP32
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://urigarciruiz34:3KlEn7zNH86yyNgc@cluster0.f9u2y6x.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
version: "1"
